---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install Coolify dependencies
  apt:
    name:
      - curl
      - git
    state: present
  become: yes

- name: Install Docker (dependency)
  include_role:
    name: docker

- name: Download Coolify installation script
  get_url:
    url: https://cdn.coollabs.io/coolify/install.sh
    dest: /tmp/coolify-install.sh
    mode: '0755'
  become: yes

- name: Run Coolify installation
  shell: bash /tmp/coolify-install.sh
  args:
    creates: /usr/local/bin/coolify
  become: yes
  register: coolify_install

- name: Display Coolify installation status
  debug:
    msg: "Coolify installation completed"

